[flavor]
dark = "everforest-medium"
# dark = "gruvbox-dk-customize"
# dark = "dracula"

[mgr]
border_symbol = " "
border_style = { fg = "#202324" }
cwd = { fg = "#7fbbb3" }
hovered = { fg = "#202324", bg = "#8DA26C", bold = true }

[indicator]
padding = { open = "█", close = "█"}

[status]
overall       = { fg = "#948A79", bg = "#272A2B" }
sep_left      = { open = " ", close = "" }
sep_right     = { open = "",  close = " " }

progress_label  = { bold = true }
progress_normal = { fg = "#7fbbb3", bg = "#232a2e" }
progress_error  = { fg = "#e67e80", bg = "#232a2e" }

perm_type  = { fg = "#a7c080" }   # t
perm_read  = { fg = "#dbbc7f" }   # r
perm_write = { fg = "#e67e80" }   # w
perm_exec  = { fg = "#7fbbb3" }   # x
perm_sep   = { fg = "#2d353b" }   # s-ish

[mode]
normal_main  = { fg = "#282828", bg = "#7DADA5", bold = true }
select_main  = { fg = "#282828", bg = "#D3869B", bold = true }
unset_main   = { bg = "#e67e80", bold = true }
normal_alt  = { fg = "#83A598", bg = "#303436" }
select_alt  = { fg = "#D3869B", bg = "#333739" }
unset_alt   = { fg = "#d3c6aa", bg = "#e67e80" }

[tabs]
active = { fg = "#282828", bg = "#81B18B", bold = true }
inactive = { fg = "#8DA26C", bg = "#2A2D2E" }
sep_inner = { open = "", close = "" }
sep_outer = { open = " ", close = " " }

[marker]
# selected = { fg = "#ffffff", bg = "#98BC83" }

[icon]
prepend_conds = [
	{ if = "dir & hovered", text = "", fg = "#a7c080"},
	{ if = "dir", text = "󰉋", fg = "#a7c080"}
]

prepend_dirs = [
	{ name = "Applications", text = "", fg = "#a7c080" },
	{ name = "CodeWork", text = "", fg = "#a7c080" },
	{ name = "Desktop", text = "", fg = "#a7c080" },
	{ name = "Documents", text = "󰂺", fg = "#a7c080" },
	{ name = "dotfiles", text = "", fg = "#a7c080" },
	{ name = "Downloads", text = "󰇚", fg = "#a7c080" },
	{ name = "Godot", text = "", fg = "#a7c080" },
	{ name = "Google Drive", text = "", fg = "#a7c080" },
	{ name = "Library", text = "", fg = "#a7c080" },
	{ name = "Movies", text = "󰟞", fg = "#a7c080" },
	{ name = "Music", text = "", fg = "#a7c080" },
	{ name = "Notes", text = "", fg = "#a7c080" },
	{ name = "Pictures", text = "", fg = "#a7c080" },
	{ name = "Public", text = "", fg = "#a7c080" },
	{ name = "Repos", text = "", fg = "#a7c080" },
]
